### ISSUE TITLE
Error downloading Forge 1.7.10-10.13.4.1614

### ISSUE THREAD

**Issue by jkoelndorfer** [jkoelndorfer/mccdl#3]
Download Project Ozone 2's current release throws an error because MultiMC's Forge configuration for that version can't be found:

    % ./mccdl 'https://mods.curse.com/modpacks/minecraft/244939-project-ozone-2-reloaded' "Project Ozone 2"
    INFO:mccdl.CurseForgeClient:Installing modpack 244939 in instance Project Ozone 2, file ID latest
    INFO:mccdl.CurseForgeProject:Fetching project 244939, file latest
    INFO:mccdl.MultiMcInstance:Creating MultiMC instance Project Ozone 2, Minecraft version 1.7.10, Forge version 10.13.4.1614
    Traceback (most recent call last):
      File "./mccdl.py", line 525, in <module>
        MccdlCommandLineApplication().run(sys.argv[1:])
      File "./mccdl.py", line 389, in run
        action_method(project_id, file_id, args.instance_name)
      File "./mccdl.py", line 73, in install_modpack
        self._setup_modpack("install", project_id, file_id, instance_name)
      File "./mccdl.py", line 101, in _setup_modpack
        setup_method(*setup_args)
      File "./mccdl.py", line 437, in create
        self.configure(minecraft_version, forge_version, icon_key=multimc_icon_key)
      File "./mccdl.py", line 422, in configure
        self._configure_instance_forge(minecraft_version, forge_version)
      File "./mccdl.py", line 474, in _configure_instance_forge
        patches_dir / "net.minecraftforge.json"
      File "./mccdl.py", line 286, in download
        cached_file_path = self._download(url)
      File "./mccdl.py", line 303, in _download
        response.raise_for_status()
      File "/home/kdorf/src/mccdl/.venv/lib/python3.6/site-packages/requests/models.py", line 909, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://meta.multimc.org/net.minecraftforge/1.7.10-10.13.4.1614.json

**Comment by jkoelndorfer** [comment]
[This repository](https://github.com/MultiMC/meta-multimc) is the repository for the metadata that mccdl is downloading. Looks like the most correct way to do this is to pull down `net.minecraftforge/index.json` and try to match the right Forge version.
